language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - TAG_LATEST=true
      DOCKER_TAG=bt
      TAG_LATEST=true
      BUILD_DIRECTORY=transmission
    - DOCKER_TAG=pt
      BUILD_DIRECTORY=transmission
      BUILD_ARGS_FILE=build_args_pt
    - TAG_SUBDIR=true
      TAG_LATEST=3.10
      BUILD_DIRECTORY=alpine
    - BUILD_DIRECTORY=pgyvpn
    - BUILD_DIRECTORY=cloud-torrent

sudo: required
  
services:
  - docker

before_script:
  - chmod +x ./hooks/*.sh

script:
  - if [[ -z ${DOCKER_USERNAME} ]]; then exit 1; fi
  - if [[ -z ${BUILD_DIRECTORY} ]]; then exit 1; fi
  - if [[ -z ${DOCKER_REPO} ]]; then DOCKER_REPO="${DOCKER_USERNAME}/${BUILD_DIRECTORY}"; fi
  - if [[ -f ${BUILD_DIRECTORY}/build.sh ]]; then bash ${BUILD_DIRECTORY}/build.sh; else ./hooks/build.sh; fi

after_success:
  - ./hooks/list.sh
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then ./hooks/upload.sh ; fi

notifications:
  email: false