language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - DOCKER_REPO=benzbrake/transmission
      DOCKER_TAG=bt
      TAG_LATEST=true
      BUILD_DIRECTORY=transmission
    - DOCKER_REPO=benzbrake/transmission
      DOCKER_TAG=pt
      BUILD_DIRECTORY=transmission
      BUILD_ARGS_FILE=build_args_pt
    - DOCKER_REPO=benzbrake/alpine
      DOCKER_TAG=3.10
      TAG_LATEST=true
      BUILD_DIRECTORY=alpine/3.10
      BUILD_ARGS_FILE=build_args_pt
    - DOCKER_REPO=benzbrake/alpine
      DOCKER_TAG=3.9
      BUILD_DIRECTORY=alpine/3.9
    - DOCKER_REPO=benzbrake/alpine
      DOCKER_TAG=3.8
      BUILD_DIRECTORY=alpine/3.8
    - DOCKER_REPO=benzbrake/alpine
      DOCKER_TAG=3.7
      BUILD_DIRECTORY=alpine/3.7
    - DOCKER_REPO=benzbrake/pgyvpn
      DOCKER_TAG=latest
      BUILD_DIRECTORY=pgyvpn
    - DOCKER_REPO=benzbrake/cloud-torrent
      DOCKER_TAG=latest
      BUILD_DIRECTORY=cloud-torrent

sudo: required
  
services:
  - docker

before_script:
  - chmod +x ./hooks/*.sh

script:
  - ./hooks/build.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" = "develop" ]]; then ./hooks/list.sh ; fi
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then ./hooks/upload.sh ; fi

branches:
  only:
    - master

notifications:
  email: false