language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - DOCKER_REPO=benzbrake/transmission
      DOCKER_TAG=bt
      TAG_LATEST=true
      BUILD_DIRECTORY=transmission
    - DOCKER_REPO=benzbrake/transmission
      DOCKER_TAG=pt
      BUILD_DIRECTORY=transmission
      BUILD_ARGS_FILE=build_args_pt
    - DOCKER_REPO=benzbrake/alpine
      DOCKER_TAG=3.10
      TAG_LATEST=true
      BUILD_DIRECTORY=alpine/3.10

sudo: required
  
services:
  - docker

before_script:
  - chmod +x ./hooks/*.sh

script:
  - ./hooks/build.sh

after_success:
  - ./hooks/upload.sh

branches:
  only:
    - master

notifications:
  email: false