language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - DOCKER_BUILD=benzbrake/transmission:bt
      BUILD_DIRECTORY=transmission
      TR_SETTINGS=settings.json
    - DOCKER_BUILD=benzbrake/transmission:pt
      BUILD_DIRECTORY=transmission
      TR_SETTINGS=settings-pt.json

sudo: required

addons:
  apt:
    update: true
  
services:
  - docker

before_script:
  - sudo apt-get -y install perl
  - chmod +x ./hooks/*.sh
script:
  - ./hooks/build.sh

after_success:
  - ./hooks/list.sh

branches:
  only:
    - master

notifications:
  email: false