version: '3'

services:
  cloud-torrent:
    image: benzbrake/cloud-torrent
    container_name: cloud-torrent
    restart: always
    volumes:
      - /data/downloads:/downloads
    ports:
      - "3000:3000"